# Changes here will be overwritten by Copier
_commit: 07dfeed
_src_path: https://github.com/DarylStark/copier_templates.git
devcontainer: true
github_workflow: true
license: MIT
package_name: macpyver_fortigate_source
project_description: 'Version Source for FortiGates for MacPyVer.

    '
project_description_short: 'Version Source for FortiGates for MacPyVer.

    '
project_name: MacPyVer - FortiGate Source
pypi_package_description: Version Source for FortiGates for MacPyVer.
pypi_package_name: macpyver_fortigate_source
sphinx_docs: true
